version: '3.7'
services:
  backend:
    build:
      context: ./node-express-mongo
      dockerfile: ./Dockerfile
    ports: 
        - "8081:8081"
    networks: 
        - integration
  frontend:
    build:
      context: ./vue-nuxt-vuetify
      dockerfile: ./Dockerfile
    ports: 
        - "4000:4000"
    networks: 
        - integration

networks: 
    integration:
        driver: bridge